seed_everything: "True"

model:
  model_conf:
  model_name: "unetrpp"
  lr: 0.1
  loss_name: "mse"
  save_path: ~
  use_lr_scheduler: "False"
  mask_ratio: 0.3
  save_weights_path: "/scratch/shared/py4cast/models/autoregressive_weights"

data:
  dataset_name: "titan"
  dataset_conf: "config/datasets/titan_full.json"
  config_override: ~