data:
  #args forwarded (linked) to model
  dataset_name: "titan"
  num_input_steps: 1
  num_pred_steps_train: 1
  num_pred_steps_train: 1
  batch_size: 2

  #other args
  num_workers: 10
  prefetch_factor: null
  pin_memory: False 
  dataset_conf: "/home/labia/leborgnelarivierec/py4cast/config/datasets/titan_refacto.json"
  config_override: null
      # num_inference_pred_steps: 6
      # periods: 
      #   test: 
      #     start: 2021061621 
      #     end: 2021061621 
      #     step: 1