seed_everything: "True"

model:
  batch_size: 4
  model_conf: 
  model_name: "unetrpp" 
  lr: 0.1
  loss_name: "mse"
  num_input_steps: 1
  num_pred_steps_train: 1
  num_pred_steps_val_test: 1
  num_samples_to_plot: 1
  training_strategy: "diff_ar"
  len_train_loader: 1
  save_path: "/scratch/shared/py4cast/logs/camp0"
  use_lr_scheduler: "False" 
  precision: "bf16"
  no_log: "False"  
  channels_last: "False" 
  save_weights_path: "/scratch/shared/py4cast/models/autoregressive_weights"

data: # Assuming dataset related parameters are moved under "data"
  dataset_name: "titan" # Replace with actual dataset name
  dataset_conf: "config/datasets/titan_full.json" # Replace with actual config path
  config_override: